version: "3.9"

services:
    web:
        container_name: assignment-server
        build: .
        restart: unless-stopped
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - app
        environment:
            - DB_CONN_STRING='mongodb://localhost:27017/dlabs-assignment'
            - ME_CONFIG_MONGODB_USERNAME=admin
            - ME_CONFIG_MONGODB_PASSWORD=admin
    
    db:
        container_name: db
        image: mongo:4.4.13
        restart: unless-stopped
        volumes:
            - db-data:/data/db/
        networks:
            - app
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin

volumes:
    db-data:

networks:
    app:
        driver: bridge
