FROM python:3.10-buster

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN apt-get update && apt-get upgrade -y
RUN apt-get install sqlite3

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY server/src /app/src/
COPY start-server.sh /app/

ENTRYPOINT [ "bash", "/app/start-server.sh" ]