version: '3.9'

services:
  server-app:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: toni
      POSTGRES_PASSWORD: strong_password
