source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "rails", "~> 7.0.4"

gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "jbuilder"
gem "bootsnap", require: false
gem "rack-cors"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]


# Custom Server-app gems
gem 'money', '~> 6.16'
gem 'monetize', '~> 1.12'
gem 'jwt'

group :development, :test do
  gem 'rspec-rails', '~> 6.0', '>= 6.0.1'
  gem 'faker', git: 'https://github.com/faker-ruby/faker', branch: 'main'
  gem 'factory_bot', '~> 6.2', '>= 6.2.1'

  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
